# Warp
# Origin date: Tue, 12 Nov 2019 15:31:14 -0800
# Local date: Tue, 12 Nov 2019 15:31:14 -0800
# Commit hash: 06ab50e
# /cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/warp.py
# /cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/warpCparallel.cpython-37m-x86_64-linux-gnu.so
# Fri Jan  3 06:21:43 2020
# 24 processors
# import warp time 1.6679933071136475 seconds
# For more help, type warphelp()
--------------------------------------------------------------------------
An MPI process has executed an operation involving a call to the
"fork()" system call to create a child process.  Open MPI is currently
operating in a condition that could result in memory corruption or
other system errors; your MPI job may hang, crash, or produce silent
data corruption.  The use of fork() (or system() or other calls that
create child processes) is strongly discouraged.  

The process that invoked fork was:

  Local host:          eu-a6-007-22 (PID 39969)
  MPI_COMM_WORLD rank: 5

If you are *absolutely sure* that your application will successfully
and correctly survive a call to fork(), you may disable this warning
by setting the mpi_warn_on_fork MCA parameter to 0.
--------------------------------------------------------------------------
('l_fftw_fort', False)
WARNING: module txphysics is not accessible.
WARNING: module desorb is not accessible.
0.0007224415584921976
Simulating ECLOUD in a crab cavity
[eu-a6-007-22:39963] 23 more processes have sent help message help-mpi-runtime.txt / mpi_init:warn-fork
[eu-a6-007-22:39963] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_10.0/complete_sim.py", line 88, in <module>
    sim = warp_pyecloud_sim(**kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 114, in __init__
    electron_background_dist = self.load_elec_density()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 360, in load_elec_density
    self.n_step = dict_init_dist['n_step'][0][0]
KeyError: 'n_step'
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_10.0/complete_sim.py", line 88, in <module>
    sim = warp_pyecloud_sim(**kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 114, in __init__
    electron_background_dist = self.load_elec_density()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 360, in load_elec_density
    self.n_step = dict_init_dist['n_step'][0][0]
KeyError: 'n_step'
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_10.0/complete_sim.py", line 88, in <module>
    sim = warp_pyecloud_sim(**kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 114, in __init__
    electron_background_dist = self.load_elec_density()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 360, in load_elec_density
    self.n_step = dict_init_dist['n_step'][0][0]
KeyError: 'n_step'
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_10.0/complete_sim.py", line 88, in <module>
    sim = warp_pyecloud_sim(**kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 114, in __init__
    electron_background_dist = self.load_elec_density()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 360, in load_elec_density
    self.n_step = dict_init_dist['n_step'][0][0]
KeyError: 'n_step'
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_10.0/complete_sim.py", line 88, in <module>
    sim = warp_pyecloud_sim(**kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 114, in __init__
    electron_background_dist = self.load_elec_density()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 360, in load_elec_density
    self.n_step = dict_init_dist['n_step'][0][0]
KeyError: 'n_step'
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_10.0/complete_sim.py", line 88, in <module>
    sim = warp_pyecloud_sim(**kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 114, in __init__
    electron_background_dist = self.load_elec_density()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 360, in load_elec_density
    self.n_step = dict_init_dist['n_step'][0][0]
KeyError: 'n_step'
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_10.0/complete_sim.py", line 88, in <module>
    sim = warp_pyecloud_sim(**kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 114, in __init__
    electron_background_dist = self.load_elec_density()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 360, in load_elec_density
    self.n_step = dict_init_dist['n_step'][0][0]
KeyError: 'n_step'
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_10.0/complete_sim.py", line 88, in <module>
    sim = warp_pyecloud_sim(**kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 114, in __init__
    electron_background_dist = self.load_elec_density()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 360, in load_elec_density
    self.n_step = dict_init_dist['n_step'][0][0]
KeyError: 'n_step'
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_10.0/complete_sim.py", line 88, in <module>
    sim = warp_pyecloud_sim(**kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 114, in __init__
    electron_background_dist = self.load_elec_density()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 360, in load_elec_density
    self.n_step = dict_init_dist['n_step'][0][0]
KeyError: 'n_step'
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_10.0/complete_sim.py", line 88, in <module>
    sim = warp_pyecloud_sim(**kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 114, in __init__
    electron_background_dist = self.load_elec_density()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 360, in load_elec_density
    self.n_step = dict_init_dist['n_step'][0][0]
KeyError: 'n_step'
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_10.0/complete_sim.py", line 88, in <module>
    sim = warp_pyecloud_sim(**kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 114, in __init__
    electron_background_dist = self.load_elec_density()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 360, in load_elec_density
    self.n_step = dict_init_dist['n_step'][0][0]
KeyError: 'n_step'
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_10.0/complete_sim.py", line 88, in <module>
    sim = warp_pyecloud_sim(**kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 114, in __init__
    electron_background_dist = self.load_elec_density()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 360, in load_elec_density
    self.n_step = dict_init_dist['n_step'][0][0]
KeyError: 'n_step'
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_10.0/complete_sim.py", line 88, in <module>
    sim = warp_pyecloud_sim(**kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 114, in __init__
    electron_background_dist = self.load_elec_density()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 360, in load_elec_density
    self.n_step = dict_init_dist['n_step'][0][0]
KeyError: 'n_step'
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_10.0/complete_sim.py", line 88, in <module>
    sim = warp_pyecloud_sim(**kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 114, in __init__
    electron_background_dist = self.load_elec_density()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 360, in load_elec_density
    self.n_step = dict_init_dist['n_step'][0][0]
KeyError: 'n_step'
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_10.0/complete_sim.py", line 88, in <module>
    sim = warp_pyecloud_sim(**kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 114, in __init__
    electron_background_dist = self.load_elec_density()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 360, in load_elec_density
    self.n_step = dict_init_dist['n_step'][0][0]
KeyError: 'n_step'
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_10.0/complete_sim.py", line 88, in <module>
    sim = warp_pyecloud_sim(**kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 114, in __init__
    electron_background_dist = self.load_elec_density()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 360, in load_elec_density
    self.n_step = dict_init_dist['n_step'][0][0]
KeyError: 'n_step'
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_10.0/complete_sim.py", line 88, in <module>
    sim = warp_pyecloud_sim(**kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 114, in __init__
    electron_background_dist = self.load_elec_density()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 360, in load_elec_density
    self.n_step = dict_init_dist['n_step'][0][0]
KeyError: 'n_step'
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_10.0/complete_sim.py", line 88, in <module>
    sim = warp_pyecloud_sim(**kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 114, in __init__
    electron_background_dist = self.load_elec_density()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 360, in load_elec_density
    self.n_step = dict_init_dist['n_step'][0][0]
KeyError: 'n_step'
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_10.0/complete_sim.py", line 88, in <module>
    sim = warp_pyecloud_sim(**kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 114, in __init__
    electron_background_dist = self.load_elec_density()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 360, in load_elec_density
    self.n_step = dict_init_dist['n_step'][0][0]
KeyError: 'n_step'
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_10.0/complete_sim.py", line 88, in <module>
    sim = warp_pyecloud_sim(**kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 114, in __init__
    electron_background_dist = self.load_elec_density()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 360, in load_elec_density
    self.n_step = dict_init_dist['n_step'][0][0]
KeyError: 'n_step'
Using cosine_3D emission angle distribution.
Secondary emission model: ECLOUD E0=150.0000 s=1.3500
#############################################################
Temp distribution found. Reloading it as initial distribution
#############################################################
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_10.0/complete_sim.py", line 88, in <module>
    sim = warp_pyecloud_sim(**kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 114, in __init__
    electron_background_dist = self.load_elec_density()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 360, in load_elec_density
    self.n_step = dict_init_dist['n_step'][0][0]
KeyError: 'n_step'
/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/warp.py:62: UserWarning: there was an error importing gist; if this is a problem, restart python and type 'import gist' for details, otherwise Warp will run OK but with no graphics
  warnings.warn("there was an error importing gist; if this is a problem, restart python and type 'import gist' for details, otherwise Warp will run OK but with no graphics")
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_10.0/complete_sim.py", line 88, in <module>
    sim = warp_pyecloud_sim(**kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 114, in __init__
    electron_background_dist = self.load_elec_density()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 360, in load_elec_density
    self.n_step = dict_init_dist['n_step'][0][0]
KeyError: 'n_step'
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_10.0/complete_sim.py", line 88, in <module>
    sim = warp_pyecloud_sim(**kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 114, in __init__
    electron_background_dist = self.load_elec_density()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 360, in load_elec_density
    self.n_step = dict_init_dist['n_step'][0][0]
KeyError: 'n_step'
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_10.0/complete_sim.py", line 88, in <module>
    sim = warp_pyecloud_sim(**kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 114, in __init__
    electron_background_dist = self.load_elec_density()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 360, in load_elec_density
    self.n_step = dict_init_dist['n_step'][0][0]
KeyError: 'n_step'
--------------------------------------------------------------------------
mpirun noticed that the job aborted, but has no info as to the process
that caused that situation.
--------------------------------------------------------------------------
# Warp
# Origin date: Thu, 2 Jan 2020 15:21:51 -0800
# Local date: Thu, 2 Jan 2020 15:21:51 -0800
# Commit hash: d24b7d7
# /cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/warp.py
# /cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/warpCparallel.cpython-37m-x86_64-linux-gnu.so
# Sun Jan  5 23:14:10 2020
# 24 processors
# import warp time 1.8939838409423828 seconds
# For more help, type warphelp()
--------------------------------------------------------------------------
An MPI process has executed an operation involving a call to the
"fork()" system call to create a child process.  Open MPI is currently
operating in a condition that could result in memory corruption or
other system errors; your MPI job may hang, crash, or produce silent
data corruption.  The use of fork() (or system() or other calls that
create child processes) is strongly discouraged.  

The process that invoked fork was:

  Local host:          eu-a6-009-03 (PID 17240)
  MPI_COMM_WORLD rank: 0

If you are *absolutely sure* that your application will successfully
and correctly survive a call to fork(), you may disable this warning
by setting the mpi_warn_on_fork MCA parameter to 0.
--------------------------------------------------------------------------
('l_fftw_fort', False)
WARNING: module txphysics is not accessible.
WARNING: module desorb is not accessible.
0.0007224415584921976
Simulating ECLOUD in a crab cavity
[eu-a6-009-03:17239] 23 more processes have sent help message help-mpi-runtime.txt / mpi_init:warn-fork
[eu-a6-009-03:17239] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
Using cosine_3D emission angle distribution.
Secondary emission model: ECLOUD E0=150.0000 s=1.3500
Plot file name complete_sim.012.cgm
 ***  particle simulation package W3D generating
 ---  Resetting lattice array sizes
 ---  Allocating space for particles
 ---  Loading particles
 ---  Setting charge density
 ---  done
 ---  Allocating Win_Moments
 ---  Allocating Z_Moments
 ---  Allocating Lab_Moments
 Atomic number of ion =  1.0073E+00
 Charge state of ion  =  1.0000E+00
 Initial X, Y emittances =  0.0000E+00,   0.0000E+00 m-rad
 Initial X,Y envelope radii  =  0.0000E+00,   0.0000E+00 m
 Initial X,Y envelope angles =  0.0000E+00,   0.0000E+00 rad
 Input beam current =  0.0000E+00 amps
 Current density =  0.0000E+00 amps/m**2
 Charge density =  0.0000E+00 Coul/m**3
 Number density =  0.0000E+00
 Plasma frequency     =  0.0000E+00 1/s
    times dt          =  0.0000E+00
    times quad period =  0.0000E+00
 Plasma period        =  6.2832E+36 s
 X-, Y-Thermal Velocities     =  0.0000E+00,   0.0000E+00 m/s
    times dt                  =  0.0000E+00,   0.0000E+00 m
    times dt/dx, dt/dy (X, Y) =  0.0000E+00,   0.0000E+00
 X-, Y-Debye Wavelengths  =  0.0000E+00,   0.0000E+00 m
    over dx, dy (X and Y) =  0.0000E+00,   0.0000E+00
 Longitudinal thermal velocity (rms) =  0.0000E+00 m/s
    times dt                   =  0.0000E+00 m
    times dt/dz                =  0.0000E+00
 Longitudinal Debye wavelength =  0.0000E+00 m
    over dz                    =  0.0000E+00
 Beam velocity =  0.0000E+00 m/s
    over c     =  0.0000E+00
 Kinetic energy =  0.0000E+00 eV
 Weight of simulation particles =  1.0000E+00
 Number of simulation particles =            0
 Number of real particles =  0.0000E+00
 Total mass =  0.0000E+00 kg
 Total charge =  0.0000E+00 Coul
 Generalized perveance =  0.0000E+00
 Characteristic current =  3.1297E+07 amps
 Budker parameter =  0.0000E+00
 Timestep size dt =  2.5000E-11 s
 Tune length =  0.0000E+00
 Undep. X-, Y-Betatron frequencies  =  6.2832E+36,   6.2832E+36 1/s
 Undep. X-, Y-Betatron periods      =  0.0000E+00,   0.0000E+00 s
 Undep. X-, Y-Betatron wavelengths  =  0.0000E+00,   0.0000E+00 m
 Dep.   X-, Y-Betatron frequencies  =  6.2832E+36,   6.2832E+36 1/s
 Dep.   X-, Y-Betatron periods      =  0.0000E+00,   0.0000E+00 s
 X-, Y-Tune Depressions (sigma/sigma0) =  0.0000E+00,   0.0000E+00
 Space charge wave velocity =  0.0000E+00 m/s
 Effective wall radius =  2.1355E-01 m
 Geometric factor =  7.9805E+01
 X-, Y-Emittance over Space charge forces =  0.0000E+00,   0.0000E+00
 Number of grid points in x =      200
 Number of grid points in y =      200
 Number of grid points in z =      100
 Grid spacing in x =  1.5100E-03 m
 Grid spacing in y =  1.2200E-03 m
 Grid spacing in z =  6.0200E-03 m
 Bend radius =  0.0000E+00 m
 Bending field =  0.0000E+00 T
 Bend length =  0.0000E+00 m
 Straight section length =  0.0000E+00 m
 Z at start of first bend =  0.0000E+00 m
it =      0 time = 0.0000E+00 pz = 0.0000E+00 ese = 0.0000E+00 ek = 0.0000E+00 et = 0.0000E+00
 ***  particle simulation package W3D running
Multigrid: Error converged to   2.805E-07 in     8 v-cycles             
it =      1 time = 2.5000E-11 pz = 0.0000E+00 ese = 6.7213E-12 ek = 0.0000E+00 et = 6.7213E-12
Multigrid: Error converged to   4.849E-07 in    13 v-cycles             
it =      2 time = 5.0000E-11 pz = 0.0000E+00 ese = 2.9665E-11 ek = 0.0000E+00 et = 2.9665E-11
Saving a checkpoint!
===========================
Bunch passage: 1
Number of electrons in the dipole: 19996733
Number of macroparticles: 4199314
10% of bunch passage
20% of bunch passage
30% of bunch passage
40% of bunch passage
50% of bunch passage
60% of bunch passage
70% of bunch passage
80% of bunch passage
90% of bunch passage
Saving a checkpoint!
===========================
Bunch passage: 2
Number of electrons in the dipole: 20757366
Number of macroparticles: 4383257
Previous passage took 1635s
10% of bunch passage
20% of bunch passage
30% of bunch passage
40% of bunch passage
50% of bunch passage
60% of bunch passage
70% of bunch passage
80% of bunch passage
90% of bunch passage
Saving a checkpoint!
===========================
Bunch passage: 3
Number of electrons in the dipole: 22000686
Number of macroparticles: 4628146
Previous passage took 1686s
10% of bunch passage
20% of bunch passage
30% of bunch passage
40% of bunch passage
50% of bunch passage
60% of bunch passage
70% of bunch passage
80% of bunch passage
90% of bunch passage
Saving a checkpoint!
===========================
Bunch passage: 4
Number of electrons in the dipole: 23484943
Number of macroparticles: 5031007
Previous passage took 1726s
10% of bunch passage
20% of bunch passage
30% of bunch passage
40% of bunch passage
50% of bunch passage
60% of bunch passage
70% of bunch passage
80% of bunch passage
90% of bunch passage
Saving a checkpoint!
===========================
Bunch passage: 5
Number of electrons in the dipole: 25332603
Number of macroparticles: 5529045
Previous passage took 1782s
10% of bunch passage
20% of bunch passage
30% of bunch passage
40% of bunch passage
50% of bunch passage
60% of bunch passage
70% of bunch passage
80% of bunch passage
90% of bunch passage
Saving a checkpoint!
===========================
Bunch passage: 6
Number of electrons in the dipole: 27918734
Number of macroparticles: 6161339
Previous passage took 1849s
10% of bunch passage
20% of bunch passage
30% of bunch passage
40% of bunch passage
50% of bunch passage
60% of bunch passage
70% of bunch passage
80% of bunch passage
90% of bunch passage
Saving a checkpoint!
===========================
Bunch passage: 7
Number of electrons in the dipole: 31568500
Number of macroparticles: 7095090
Previous passage took 1935s
10% of bunch passage
20% of bunch passage
30% of bunch passage
40% of bunch passage
50% of bunch passage
60% of bunch passage
70% of bunch passage
80% of bunch passage
90% of bunch passage
Number of macroparticles: 6192564
MAXIMUM LIMIT OF MPS HAS BEEN RACHED
New nel_mp_ref = 13
Start SOFT regeneration. N_mp=6192564 Nel_tot=2.65e+07, En_tot = 2.74e+08
Applied correction factor = 3.095969e+00
Done SOFT regeneration. N_mp=2000231 Nel_tot=2.65e+07 En_tot=2.74e+08
Saving a checkpoint!
===========================
Bunch passage: 8
Number of electrons in the dipole: 36672887
Number of macroparticles: 4134863
Previous passage took 2066s
10% of bunch passage
20% of bunch passage
30% of bunch passage
40% of bunch passage
50% of bunch passage
60% of bunch passage
70% of bunch passage
80% of bunch passage
90% of bunch passage
Saving a checkpoint!
===========================
Bunch passage: 9
Number of electrons in the dipole: 43704603
Number of macroparticles: 4785923
Previous passage took 1578s
10% of bunch passage
20% of bunch passage
30% of bunch passage
40% of bunch passage
50% of bunch passage
60% of bunch passage
70% of bunch passage
80% of bunch passage
90% of bunch passage
Saving a checkpoint!
===========================
Bunch passage: 10
Number of electrons in the dipole: 53287647
Number of macroparticles: 5556827
Previous passage took 1682s
10% of bunch passage
20% of bunch passage
30% of bunch passage
40% of bunch passage
50% of bunch passage
60% of bunch passage
70% of bunch passage
80% of bunch passage
90% of bunch passage
Saving a checkpoint!
===========================
Bunch passage: 11
Number of electrons in the dipole: 66464440
Number of macroparticles: 6615906
Previous passage took 1830s
10% of bunch passage
20% of bunch passage
30% of bunch passage
40% of bunch passage
50% of bunch passage
60% of bunch passage
70% of bunch passage
80% of bunch passage
90% of bunch passage
Number of macroparticles: 6662341
MAXIMUM LIMIT OF MPS HAS BEEN RACHED
New nel_mp_ref = 39
Start SOFT regeneration. N_mp=6662341 Nel_tot=7.80e+07, En_tot = 7.80e+08
Applied correction factor = 3.333305e+00
Done SOFT regeneration. N_mp=1999023 Nel_tot=7.80e+07 En_tot=7.80e+08
Saving a checkpoint!
===========================
Bunch passage: 12
Number of electrons in the dipole: 84579343
Number of macroparticles: 3376679
Previous passage took 2046s
10% of bunch passage
20% of bunch passage
30% of bunch passage
40% of bunch passage
50% of bunch passage
60% of bunch passage
70% of bunch passage
80% of bunch passage
90% of bunch passage
Saving a checkpoint!
===========================
Bunch passage: 13
Number of electrons in the dipole: 109299598
Number of macroparticles: 4178092
Previous passage took 1533s
10% of bunch passage
20% of bunch passage
30% of bunch passage
40% of bunch passage
50% of bunch passage
60% of bunch passage
70% of bunch passage
80% of bunch passage
90% of bunch passage
Saving a checkpoint!
===========================
Bunch passage: 14
Number of electrons in the dipole: 142774141
Number of macroparticles: 5090438
Previous passage took 1677s
10% of bunch passage
20% of bunch passage
30% of bunch passage
40% of bunch passage
50% of bunch passage
60% of bunch passage
70% of bunch passage
80% of bunch passage
90% of bunch passage
Saving a checkpoint!
===========================
Bunch passage: 15
Number of electrons in the dipole: 187608512
Number of macroparticles: 6295576
Previous passage took 1865s
10% of bunch passage
20% of bunch passage
30% of bunch passage
40% of bunch passage
50% of bunch passage
60% of bunch passage
70% of bunch passage
80% of bunch passage
90% of bunch passage
Number of macroparticles: 6905134
MAXIMUM LIMIT OF MPS HAS BEEN RACHED
New nel_mp_ref = 120
Start SOFT regeneration. N_mp=6905134 Nel_tot=2.42e+08, En_tot = 2.36e+09
Applied correction factor = 3.452231e+00
Done SOFT regeneration. N_mp=2000789 Nel_tot=2.42e+08 En_tot=2.37e+09
Saving a checkpoint!
===========================
Bunch passage: 16
Number of electrons in the dipole: 246603232
Number of macroparticles: 2987374
Previous passage took 2113s
10% of bunch passage
20% of bunch passage
30% of bunch passage
40% of bunch passage
50% of bunch passage
60% of bunch passage
70% of bunch passage
80% of bunch passage
90% of bunch passage
Saving a checkpoint!
===========================
Bunch passage: 17
Number of electrons in the dipole: 322556644
Number of macroparticles: 3788782
Previous passage took 1520s
10% of bunch passage
20% of bunch passage
30% of bunch passage
40% of bunch passage
50% of bunch passage
60% of bunch passage
70% of bunch passage
80% of bunch passage
90% of bunch passage
Saving a checkpoint!
===========================
Bunch passage: 18
Number of electrons in the dipole: 417332183
Number of macroparticles: 4660860
Previous passage took 1657s
10% of bunch passage
20% of bunch passage
30% of bunch passage
40% of bunch passage
50% of bunch passage
60% of bunch passage
70% of bunch passage
80% of bunch passage
90% of bunch passage
Saving a checkpoint!
===========================
Bunch passage: 19
Number of electrons in the dipole: 531169261
Number of macroparticles: 5735972
Previous passage took 1829s
10% of bunch passage
20% of bunch passage
30% of bunch passage
40% of bunch passage
50% of bunch passage
60% of bunch passage
70% of bunch passage
80% of bunch passage
90% of bunch passage
Number of macroparticles: 6306970
MAXIMUM LIMIT OF MPS HAS BEEN RACHED
New nel_mp_ref = 329
Start SOFT regeneration. N_mp=6306970 Nel_tot=6.59e+08, En_tot = 6.66e+09
Applied correction factor = 3.155908e+00
Done SOFT regeneration. N_mp=1998408 Nel_tot=6.59e+08 En_tot=6.65e+09
Saving a checkpoint!
===========================
Bunch passage: 20
Number of electrons in the dipole: 662563324
Number of macroparticles: 2724256
Previous passage took 2047s
10% of bunch passage
20% of bunch passage
30% of bunch passage
40% of bunch passage
50% of bunch passage
60% of bunch passage
70% of bunch passage
80% of bunch passage
90% of bunch passage
Saving a checkpoint!
===========================
Bunch passage: 21
Number of electrons in the dipole: 808047237
Number of macroparticles: 3435834
Previous passage took 1489s
10% of bunch passage
20% of bunch passage
30% of bunch passage
40% of bunch passage
50% of bunch passage
60% of bunch passage
70% of bunch passage
80% of bunch passage
90% of bunch passage
Saving a checkpoint!
===========================
Bunch passage: 22
Number of electrons in the dipole: 963216938
Number of macroparticles: 4089931
Previous passage took 1572s
10% of bunch passage
20% of bunch passage
30% of bunch passage
40% of bunch passage
50% of bunch passage
60% of bunch passage
70% of bunch passage
80% of bunch passage
90% of bunch passage
Saving a checkpoint!
===========================
Bunch passage: 23
Number of electrons in the dipole: 1123329923
Number of macroparticles: 4793457
Previous passage took 1680s
10% of bunch passage
20% of bunch passage
30% of bunch passage
40% of bunch passage
50% of bunch passage
60% of bunch passage
70% of bunch passage
80% of bunch passage
90% of bunch passage
Saving a checkpoint!
===========================
Bunch passage: 24
Number of electrons in the dipole: 1284035275
Number of macroparticles: 5543947
Previous passage took 1811s
10% of bunch passage
20% of bunch passage
30% of bunch passage
40% of bunch passage
50% of bunch passage
60% of bunch passage
70% of bunch passage
80% of bunch passage
90% of bunch passage
Saving a checkpoint!
===========================
Bunch passage: 25
Number of electrons in the dipole: 1441699541
Number of macroparticles: 6331621
Previous passage took 1930s
10% of bunch passage
20% of bunch passage
30% of bunch passage
40% of bunch passage
50% of bunch passage
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_10.0/complete_sim.py", line 90, in <module>
    sim.all_steps()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 303, in all_steps
    self.step(self.tot_nsteps-self.n_step)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 281, in step
    picmi.warp.step(1)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/ctl.py", line 97, in step
    controllers.callafterstepfuncs()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/controllers.py", line 102, in __call__
    tt = self.callfuncsinlist(*args,**kw)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/controllers.py", line 268, in callfuncsinlist
    f(*args,**kw)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 422, in myplots
    plt.savefig(figname)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/pyplot.py", line 722, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/figure.py", line 2180, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 2089, in print_figure
    **kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 530, in print_png
    cbook.open_file_cm(filename_or_obj, "wb") as fh:
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/python3/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 447, in open_file_cm
    fh, opened = to_filehandle(path_or_file, mode, True, encoding)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 432, in to_filehandle
    fh = open(fname, flag, encoding=encoding)
OSError: [Errno 122] Disk quota exceeded: '/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_10.0/images/24522.png'
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_10.0/complete_sim.py", line 90, in <module>
    sim.all_steps()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 303, in all_steps
    self.step(self.tot_nsteps-self.n_step)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 281, in step
    picmi.warp.step(1)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/ctl.py", line 97, in step
    controllers.callafterstepfuncs()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/controllers.py", line 102, in __call__
    tt = self.callfuncsinlist(*args,**kw)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/controllers.py", line 268, in callfuncsinlist
    f(*args,**kw)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 422, in myplots
    plt.savefig(figname)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/pyplot.py", line 722, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/figure.py", line 2180, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 2089, in print_figure
    **kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 530, in print_png
    cbook.open_file_cm(filename_or_obj, "wb") as fh:
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/python3/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 447, in open_file_cm
    fh, opened = to_filehandle(path_or_file, mode, True, encoding)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 432, in to_filehandle
    fh = open(fname, flag, encoding=encoding)
OSError: [Errno 122] Disk quota exceeded: '/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_10.0/images/24522.png'
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_10.0/complete_sim.py", line 90, in <module>
    sim.all_steps()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 303, in all_steps
    self.step(self.tot_nsteps-self.n_step)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 281, in step
    picmi.warp.step(1)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/ctl.py", line 97, in step
    controllers.callafterstepfuncs()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/controllers.py", line 102, in __call__
    tt = self.callfuncsinlist(*args,**kw)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/controllers.py", line 268, in callfuncsinlist
    f(*args,**kw)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 422, in myplots
    plt.savefig(figname)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/pyplot.py", line 722, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/figure.py", line 2180, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 2089, in print_figure
    **kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 530, in print_png
    cbook.open_file_cm(filename_or_obj, "wb") as fh:
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/python3/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 447, in open_file_cm
    fh, opened = to_filehandle(path_or_file, mode, True, encoding)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 432, in to_filehandle
    fh = open(fname, flag, encoding=encoding)
OSError: [Errno 122] Disk quota exceeded: '/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_10.0/images/24522.png'
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_10.0/complete_sim.py", line 90, in <module>
    sim.all_steps()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 303, in all_steps
    self.step(self.tot_nsteps-self.n_step)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 281, in step
    picmi.warp.step(1)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/ctl.py", line 97, in step
    controllers.callafterstepfuncs()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/controllers.py", line 102, in __call__
    tt = self.callfuncsinlist(*args,**kw)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/controllers.py", line 268, in callfuncsinlist
    f(*args,**kw)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 422, in myplots
    plt.savefig(figname)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/pyplot.py", line 722, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/figure.py", line 2180, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 2089, in print_figure
    **kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 530, in print_png
    cbook.open_file_cm(filename_or_obj, "wb") as fh:
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/python3/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 447, in open_file_cm
    fh, opened = to_filehandle(path_or_file, mode, True, encoding)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 432, in to_filehandle
    fh = open(fname, flag, encoding=encoding)
OSError: [Errno 122] Disk quota exceeded: '/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_10.0/images/24522.png'
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_10.0/complete_sim.py", line 90, in <module>
    sim.all_steps()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 303, in all_steps
    self.step(self.tot_nsteps-self.n_step)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 281, in step
    picmi.warp.step(1)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/ctl.py", line 97, in step
    controllers.callafterstepfuncs()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/controllers.py", line 102, in __call__
    tt = self.callfuncsinlist(*args,**kw)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/controllers.py", line 268, in callfuncsinlist
    f(*args,**kw)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 422, in myplots
    plt.savefig(figname)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/pyplot.py", line 722, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/figure.py", line 2180, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 2089, in print_figure
    **kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 530, in print_png
    cbook.open_file_cm(filename_or_obj, "wb") as fh:
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/python3/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 447, in open_file_cm
    fh, opened = to_filehandle(path_or_file, mode, True, encoding)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 432, in to_filehandle
    fh = open(fname, flag, encoding=encoding)
OSError: [Errno 122] Disk quota exceeded: '/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_10.0/images/24522.png'
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_10.0/complete_sim.py", line 90, in <module>
    sim.all_steps()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 303, in all_steps
    self.step(self.tot_nsteps-self.n_step)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 281, in step
    picmi.warp.step(1)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/ctl.py", line 97, in step
    controllers.callafterstepfuncs()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/controllers.py", line 102, in __call__
    tt = self.callfuncsinlist(*args,**kw)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/controllers.py", line 268, in callfuncsinlist
    f(*args,**kw)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 422, in myplots
    plt.savefig(figname)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/pyplot.py", line 722, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/figure.py", line 2180, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 2089, in print_figure
    **kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 530, in print_png
    cbook.open_file_cm(filename_or_obj, "wb") as fh:
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/python3/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 447, in open_file_cm
    fh, opened = to_filehandle(path_or_file, mode, True, encoding)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 432, in to_filehandle
    fh = open(fname, flag, encoding=encoding)
OSError: [Errno 122] Disk quota exceeded: '/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_10.0/images/24522.png'
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_10.0/complete_sim.py", line 90, in <module>
    sim.all_steps()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 303, in all_steps
    self.step(self.tot_nsteps-self.n_step)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 281, in step
    picmi.warp.step(1)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/ctl.py", line 97, in step
    controllers.callafterstepfuncs()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/controllers.py", line 102, in __call__
    tt = self.callfuncsinlist(*args,**kw)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/controllers.py", line 268, in callfuncsinlist
    f(*args,**kw)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 422, in myplots
    plt.savefig(figname)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/pyplot.py", line 722, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/figure.py", line 2180, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 2089, in print_figure
    **kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 530, in print_png
    cbook.open_file_cm(filename_or_obj, "wb") as fh:
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/python3/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 447, in open_file_cm
    fh, opened = to_filehandle(path_or_file, mode, True, encoding)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 432, in to_filehandle
    fh = open(fname, flag, encoding=encoding)
OSError: [Errno 122] Disk quota exceeded: '/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_10.0/images/24522.png'
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_10.0/complete_sim.py", line 90, in <module>
    sim.all_steps()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 303, in all_steps
    self.step(self.tot_nsteps-self.n_step)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 281, in step
    picmi.warp.step(1)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/ctl.py", line 97, in step
    controllers.callafterstepfuncs()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/controllers.py", line 102, in __call__
    tt = self.callfuncsinlist(*args,**kw)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/controllers.py", line 268, in callfuncsinlist
    f(*args,**kw)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 422, in myplots
    plt.savefig(figname)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/pyplot.py", line 722, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/figure.py", line 2180, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 2089, in print_figure
    **kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 530, in print_png
    cbook.open_file_cm(filename_or_obj, "wb") as fh:
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/python3/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 447, in open_file_cm
    fh, opened = to_filehandle(path_or_file, mode, True, encoding)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 432, in to_filehandle
    fh = open(fname, flag, encoding=encoding)
OSError: [Errno 122] Disk quota exceeded: '/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_10.0/images/24522.png'
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_10.0/complete_sim.py", line 90, in <module>
    sim.all_steps()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 303, in all_steps
    self.step(self.tot_nsteps-self.n_step)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 281, in step
    picmi.warp.step(1)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/ctl.py", line 97, in step
    controllers.callafterstepfuncs()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/controllers.py", line 102, in __call__
    tt = self.callfuncsinlist(*args,**kw)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/controllers.py", line 268, in callfuncsinlist
    f(*args,**kw)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 422, in myplots
    plt.savefig(figname)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/pyplot.py", line 722, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/figure.py", line 2180, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 2089, in print_figure
    **kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 530, in print_png
    cbook.open_file_cm(filename_or_obj, "wb") as fh:
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/python3/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 447, in open_file_cm
    fh, opened = to_filehandle(path_or_file, mode, True, encoding)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 432, in to_filehandle
    fh = open(fname, flag, encoding=encoding)
OSError: [Errno 122] Disk quota exceeded: '/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_10.0/images/24522.png'
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_10.0/complete_sim.py", line 90, in <module>
    sim.all_steps()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 303, in all_steps
    self.step(self.tot_nsteps-self.n_step)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 281, in step
    picmi.warp.step(1)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/ctl.py", line 97, in step
    controllers.callafterstepfuncs()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/controllers.py", line 102, in __call__
    tt = self.callfuncsinlist(*args,**kw)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/controllers.py", line 268, in callfuncsinlist
    f(*args,**kw)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 422, in myplots
    plt.savefig(figname)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/pyplot.py", line 722, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/figure.py", line 2180, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 2089, in print_figure
    **kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 530, in print_png
    cbook.open_file_cm(filename_or_obj, "wb") as fh:
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/python3/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 447, in open_file_cm
    fh, opened = to_filehandle(path_or_file, mode, True, encoding)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 432, in to_filehandle
    fh = open(fname, flag, encoding=encoding)
OSError: [Errno 122] Disk quota exceeded: '/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_10.0/images/24522.png'
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_10.0/complete_sim.py", line 90, in <module>
    sim.all_steps()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 303, in all_steps
    self.step(self.tot_nsteps-self.n_step)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 281, in step
    picmi.warp.step(1)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/ctl.py", line 97, in step
    controllers.callafterstepfuncs()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/controllers.py", line 102, in __call__
    tt = self.callfuncsinlist(*args,**kw)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/controllers.py", line 268, in callfuncsinlist
    f(*args,**kw)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 422, in myplots
    plt.savefig(figname)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/pyplot.py", line 722, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/figure.py", line 2180, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 2089, in print_figure
    **kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 530, in print_png
    cbook.open_file_cm(filename_or_obj, "wb") as fh:
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/python3/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 447, in open_file_cm
    fh, opened = to_filehandle(path_or_file, mode, True, encoding)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 432, in to_filehandle
    fh = open(fname, flag, encoding=encoding)
OSError: [Errno 122] Disk quota exceeded: '/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_10.0/images/24522.png'
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_10.0/complete_sim.py", line 90, in <module>
    sim.all_steps()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 303, in all_steps
    self.step(self.tot_nsteps-self.n_step)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 281, in step
    picmi.warp.step(1)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/ctl.py", line 97, in step
    controllers.callafterstepfuncs()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/controllers.py", line 102, in __call__
    tt = self.callfuncsinlist(*args,**kw)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/controllers.py", line 268, in callfuncsinlist
    f(*args,**kw)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 422, in myplots
    plt.savefig(figname)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/pyplot.py", line 722, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/figure.py", line 2180, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 2089, in print_figure
    **kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 530, in print_png
    cbook.open_file_cm(filename_or_obj, "wb") as fh:
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/python3/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 447, in open_file_cm
    fh, opened = to_filehandle(path_or_file, mode, True, encoding)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 432, in to_filehandle
    fh = open(fname, flag, encoding=encoding)
OSError: [Errno 122] Disk quota exceeded: '/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_10.0/images/24522.png'
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_10.0/complete_sim.py", line 90, in <module>
    sim.all_steps()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 303, in all_steps
    self.step(self.tot_nsteps-self.n_step)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 281, in step
    picmi.warp.step(1)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/ctl.py", line 97, in step
    controllers.callafterstepfuncs()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/controllers.py", line 102, in __call__
    tt = self.callfuncsinlist(*args,**kw)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/controllers.py", line 268, in callfuncsinlist
    f(*args,**kw)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 422, in myplots
    plt.savefig(figname)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/pyplot.py", line 722, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/figure.py", line 2180, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 2089, in print_figure
    **kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 530, in print_png
    cbook.open_file_cm(filename_or_obj, "wb") as fh:
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/python3/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 447, in open_file_cm
    fh, opened = to_filehandle(path_or_file, mode, True, encoding)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 432, in to_filehandle
    fh = open(fname, flag, encoding=encoding)
OSError: [Errno 122] Disk quota exceeded: '/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_10.0/images/24522.png'
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_10.0/complete_sim.py", line 90, in <module>
    sim.all_steps()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 303, in all_steps
    self.step(self.tot_nsteps-self.n_step)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 281, in step
    picmi.warp.step(1)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/ctl.py", line 97, in step
    controllers.callafterstepfuncs()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/controllers.py", line 102, in __call__
    tt = self.callfuncsinlist(*args,**kw)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/controllers.py", line 268, in callfuncsinlist
    f(*args,**kw)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 422, in myplots
    plt.savefig(figname)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/pyplot.py", line 722, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/figure.py", line 2180, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 2089, in print_figure
    **kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 530, in print_png
    cbook.open_file_cm(filename_or_obj, "wb") as fh:
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/python3/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 447, in open_file_cm
    fh, opened = to_filehandle(path_or_file, mode, True, encoding)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 432, in to_filehandle
    fh = open(fname, flag, encoding=encoding)
OSError: [Errno 122] Disk quota exceeded: '/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_10.0/images/24522.png'
/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/warp.py:62: UserWarning: there was an error importing gist; if this is a problem, restart python and type 'import gist' for details, otherwise Warp will run OK but with no graphics
  warnings.warn("there was an error importing gist; if this is a problem, restart python and type 'import gist' for details, otherwise Warp will run OK but with no graphics")
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_10.0/complete_sim.py", line 90, in <module>
    sim.all_steps()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 303, in all_steps
    self.step(self.tot_nsteps-self.n_step)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 281, in step
    picmi.warp.step(1)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/ctl.py", line 97, in step
    controllers.callafterstepfuncs()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/controllers.py", line 102, in __call__
    tt = self.callfuncsinlist(*args,**kw)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/controllers.py", line 268, in callfuncsinlist
    f(*args,**kw)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 422, in myplots
    plt.savefig(figname)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/pyplot.py", line 722, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/figure.py", line 2180, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 2089, in print_figure
    **kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 530, in print_png
    cbook.open_file_cm(filename_or_obj, "wb") as fh:
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/python3/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 447, in open_file_cm
    fh, opened = to_filehandle(path_or_file, mode, True, encoding)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 432, in to_filehandle
    fh = open(fname, flag, encoding=encoding)
OSError: [Errno 122] Disk quota exceeded: '/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_10.0/images/24522.png'
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_10.0/complete_sim.py", line 90, in <module>
    sim.all_steps()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 303, in all_steps
    self.step(self.tot_nsteps-self.n_step)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 281, in step
    picmi.warp.step(1)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/ctl.py", line 97, in step
    controllers.callafterstepfuncs()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/controllers.py", line 102, in __call__
    tt = self.callfuncsinlist(*args,**kw)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/controllers.py", line 268, in callfuncsinlist
    f(*args,**kw)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 422, in myplots
    plt.savefig(figname)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/pyplot.py", line 722, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/figure.py", line 2180, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 2089, in print_figure
    **kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 530, in print_png
    cbook.open_file_cm(filename_or_obj, "wb") as fh:
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/python3/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 447, in open_file_cm
    fh, opened = to_filehandle(path_or_file, mode, True, encoding)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 432, in to_filehandle
    fh = open(fname, flag, encoding=encoding)
OSError: [Errno 122] Disk quota exceeded: '/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_10.0/images/24522.png'
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_10.0/complete_sim.py", line 90, in <module>
    sim.all_steps()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 303, in all_steps
    self.step(self.tot_nsteps-self.n_step)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 281, in step
    picmi.warp.step(1)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/ctl.py", line 97, in step
    controllers.callafterstepfuncs()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/controllers.py", line 102, in __call__
    tt = self.callfuncsinlist(*args,**kw)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/controllers.py", line 268, in callfuncsinlist
    f(*args,**kw)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 422, in myplots
    plt.savefig(figname)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/pyplot.py", line 722, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/figure.py", line 2180, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 2089, in print_figure
    **kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 530, in print_png
    cbook.open_file_cm(filename_or_obj, "wb") as fh:
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/python3/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 447, in open_file_cm
    fh, opened = to_filehandle(path_or_file, mode, True, encoding)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 432, in to_filehandle
    fh = open(fname, flag, encoding=encoding)
OSError: [Errno 122] Disk quota exceeded: '/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_10.0/images/24522.png'
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_10.0/complete_sim.py", line 90, in <module>
    sim.all_steps()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 303, in all_steps
    self.step(self.tot_nsteps-self.n_step)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 281, in step
    picmi.warp.step(1)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/ctl.py", line 97, in step
    controllers.callafterstepfuncs()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/controllers.py", line 102, in __call__
    tt = self.callfuncsinlist(*args,**kw)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/controllers.py", line 268, in callfuncsinlist
    f(*args,**kw)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 422, in myplots
    plt.savefig(figname)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/pyplot.py", line 722, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/figure.py", line 2180, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 2089, in print_figure
    **kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 530, in print_png
    cbook.open_file_cm(filename_or_obj, "wb") as fh:
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/python3/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 447, in open_file_cm
    fh, opened = to_filehandle(path_or_file, mode, True, encoding)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 432, in to_filehandle
    fh = open(fname, flag, encoding=encoding)
OSError: [Errno 122] Disk quota exceeded: '/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_10.0/images/24522.png'
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_10.0/complete_sim.py", line 90, in <module>
    sim.all_steps()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 303, in all_steps
    self.step(self.tot_nsteps-self.n_step)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 281, in step
    picmi.warp.step(1)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/ctl.py", line 97, in step
    controllers.callafterstepfuncs()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/controllers.py", line 102, in __call__
    tt = self.callfuncsinlist(*args,**kw)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/controllers.py", line 268, in callfuncsinlist
    f(*args,**kw)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 422, in myplots
    plt.savefig(figname)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/pyplot.py", line 722, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/figure.py", line 2180, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 2089, in print_figure
    **kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 530, in print_png
    cbook.open_file_cm(filename_or_obj, "wb") as fh:
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/python3/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 447, in open_file_cm
    fh, opened = to_filehandle(path_or_file, mode, True, encoding)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 432, in to_filehandle
    fh = open(fname, flag, encoding=encoding)
OSError: [Errno 122] Disk quota exceeded: '/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_10.0/images/24522.png'
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_10.0/complete_sim.py", line 90, in <module>
    sim.all_steps()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 303, in all_steps
    self.step(self.tot_nsteps-self.n_step)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 281, in step
    picmi.warp.step(1)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/ctl.py", line 97, in step
    controllers.callafterstepfuncs()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/controllers.py", line 102, in __call__
    tt = self.callfuncsinlist(*args,**kw)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/controllers.py", line 268, in callfuncsinlist
    f(*args,**kw)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 422, in myplots
    plt.savefig(figname)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/pyplot.py", line 722, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/figure.py", line 2180, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 2089, in print_figure
    **kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 530, in print_png
    cbook.open_file_cm(filename_or_obj, "wb") as fh:
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/python3/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 447, in open_file_cm
    fh, opened = to_filehandle(path_or_file, mode, True, encoding)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 432, in to_filehandle
    fh = open(fname, flag, encoding=encoding)
OSError: [Errno 122] Disk quota exceeded: '/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_10.0/images/24522.png'
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_10.0/complete_sim.py", line 90, in <module>
    sim.all_steps()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 303, in all_steps
    self.step(self.tot_nsteps-self.n_step)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 281, in step
    picmi.warp.step(1)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/ctl.py", line 97, in step
    controllers.callafterstepfuncs()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/controllers.py", line 102, in __call__
    tt = self.callfuncsinlist(*args,**kw)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/controllers.py", line 268, in callfuncsinlist
    f(*args,**kw)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 422, in myplots
    plt.savefig(figname)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/pyplot.py", line 722, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/figure.py", line 2180, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 2089, in print_figure
    **kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 530, in print_png
    cbook.open_file_cm(filename_or_obj, "wb") as fh:
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/python3/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 447, in open_file_cm
    fh, opened = to_filehandle(path_or_file, mode, True, encoding)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 432, in to_filehandle
    fh = open(fname, flag, encoding=encoding)
OSError: [Errno 122] Disk quota exceeded: '/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_10.0/images/24522.png'
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_10.0/complete_sim.py", line 90, in <module>
    sim.all_steps()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 303, in all_steps
    self.step(self.tot_nsteps-self.n_step)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 281, in step
    picmi.warp.step(1)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/ctl.py", line 97, in step
    controllers.callafterstepfuncs()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/controllers.py", line 102, in __call__
    tt = self.callfuncsinlist(*args,**kw)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/controllers.py", line 268, in callfuncsinlist
    f(*args,**kw)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 422, in myplots
    plt.savefig(figname)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/pyplot.py", line 722, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/figure.py", line 2180, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 2089, in print_figure
    **kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 530, in print_png
    cbook.open_file_cm(filename_or_obj, "wb") as fh:
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/python3/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 447, in open_file_cm
    fh, opened = to_filehandle(path_or_file, mode, True, encoding)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 432, in to_filehandle
    fh = open(fname, flag, encoding=encoding)
OSError: [Errno 122] Disk quota exceeded: '/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_10.0/images/24522.png'
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_10.0/complete_sim.py", line 90, in <module>
    sim.all_steps()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 303, in all_steps
    self.step(self.tot_nsteps-self.n_step)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 281, in step
    picmi.warp.step(1)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/ctl.py", line 97, in step
    controllers.callafterstepfuncs()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/controllers.py", line 102, in __call__
    tt = self.callfuncsinlist(*args,**kw)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/controllers.py", line 268, in callfuncsinlist
    f(*args,**kw)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 422, in myplots
    plt.savefig(figname)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/pyplot.py", line 722, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/figure.py", line 2180, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 2089, in print_figure
    **kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 530, in print_png
    cbook.open_file_cm(filename_or_obj, "wb") as fh:
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/python3/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 447, in open_file_cm
    fh, opened = to_filehandle(path_or_file, mode, True, encoding)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 432, in to_filehandle
    fh = open(fname, flag, encoding=encoding)
OSError: [Errno 122] Disk quota exceeded: '/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_10.0/images/24522.png'
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_10.0/complete_sim.py", line 90, in <module>
    sim.all_steps()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 303, in all_steps
    self.step(self.tot_nsteps-self.n_step)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 281, in step
    picmi.warp.step(1)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/ctl.py", line 97, in step
    controllers.callafterstepfuncs()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/controllers.py", line 102, in __call__
    tt = self.callfuncsinlist(*args,**kw)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/controllers.py", line 268, in callfuncsinlist
    f(*args,**kw)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 422, in myplots
    plt.savefig(figname)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/pyplot.py", line 722, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/figure.py", line 2180, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 2089, in print_figure
    **kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 530, in print_png
    cbook.open_file_cm(filename_or_obj, "wb") as fh:
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/python3/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 447, in open_file_cm
    fh, opened = to_filehandle(path_or_file, mode, True, encoding)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 432, in to_filehandle
    fh = open(fname, flag, encoding=encoding)
OSError: [Errno 122] Disk quota exceeded: '/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_10.0/images/24522.png'
--------------------------------------------------------------------------
mpirun noticed that the job aborted, but has no info as to the process
that caused that situation.
--------------------------------------------------------------------------
