# Warp
# Origin date: Thu, 2 Jan 2020 15:21:51 -0800
# Local date: Thu, 2 Jan 2020 15:21:51 -0800
# Commit hash: d24b7d7
# /cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/warp.py
# /cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/warpCparallel.cpython-37m-x86_64-linux-gnu.so
# Tue Jan  7 09:13:02 2020
# 24 processors
# import warp time 1.6996562480926514 seconds
# For more help, type warphelp()
--------------------------------------------------------------------------
An MPI process has executed an operation involving a call to the
"fork()" system call to create a child process.  Open MPI is currently
operating in a condition that could result in memory corruption or
other system errors; your MPI job may hang, crash, or produce silent
data corruption.  The use of fork() (or system() or other calls that
create child processes) is strongly discouraged.  

The process that invoked fork was:

  Local host:          eu-a6-001-07 (PID 14557)
  MPI_COMM_WORLD rank: 4

If you are *absolutely sure* that your application will successfully
and correctly survive a call to fork(), you may disable this warning
by setting the mpi_warn_on_fork MCA parameter to 0.
--------------------------------------------------------------------------
('l_fftw_fort', False)
WARNING: module txphysics is not accessible.
WARNING: module desorb is not accessible.
0.0007224415584921976
/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/warp.py:62: UserWarning: there was an error importing gist; if this is a problem, restart python and type 'import gist' for details, otherwise Warp will run OK but with no graphics
  warnings.warn("there was an error importing gist; if this is a problem, restart python and type 'import gist' for details, otherwise Warp will run OK but with no graphics")
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_55.0/complete_sim.py", line 42, in <module>
    fields_folder = str(Path(os.getcwd()).parent.parent.parent.parent)
NameError: name 'Path' is not defined
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_55.0/complete_sim.py", line 42, in <module>
    fields_folder = str(Path(os.getcwd()).parent.parent.parent.parent)
NameError: name 'Path' is not defined
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_55.0/complete_sim.py", line 42, in <module>
    fields_folder = str(Path(os.getcwd()).parent.parent.parent.parent)
NameError: name 'Path' is not defined
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_55.0/complete_sim.py", line 42, in <module>
    fields_folder = str(Path(os.getcwd()).parent.parent.parent.parent)
NameError: name 'Path' is not defined
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_55.0/complete_sim.py", line 42, in <module>
    fields_folder = str(Path(os.getcwd()).parent.parent.parent.parent)
NameError: name 'Path' is not defined
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_55.0/complete_sim.py", line 42, in <module>
    fields_folder = str(Path(os.getcwd()).parent.parent.parent.parent)
NameError: name 'Path' is not defined
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_55.0/complete_sim.py", line 42, in <module>
    fields_folder = str(Path(os.getcwd()).parent.parent.parent.parent)
NameError: name 'Path' is not defined
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_55.0/complete_sim.py", line 42, in <module>
    fields_folder = str(Path(os.getcwd()).parent.parent.parent.parent)
NameError: name 'Path' is not defined
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_55.0/complete_sim.py", line 42, in <module>
    fields_folder = str(Path(os.getcwd()).parent.parent.parent.parent)
NameError: name 'Path' is not defined
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_55.0/complete_sim.py", line 42, in <module>
    fields_folder = str(Path(os.getcwd()).parent.parent.parent.parent)
NameError: name 'Path' is not defined
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_55.0/complete_sim.py", line 42, in <module>
    fields_folder = str(Path(os.getcwd()).parent.parent.parent.parent)
NameError: name 'Path' is not defined
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_55.0/complete_sim.py", line 42, in <module>
    fields_folder = str(Path(os.getcwd()).parent.parent.parent.parent)
NameError: name 'Path' is not defined
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_55.0/complete_sim.py", line 42, in <module>
    fields_folder = str(Path(os.getcwd()).parent.parent.parent.parent)
NameError: name 'Path' is not defined
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_55.0/complete_sim.py", line 42, in <module>
    fields_folder = str(Path(os.getcwd()).parent.parent.parent.parent)
NameError: name 'Path' is not defined
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_55.0/complete_sim.py", line 42, in <module>
    fields_folder = str(Path(os.getcwd()).parent.parent.parent.parent)
NameError: name 'Path' is not defined
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_55.0/complete_sim.py", line 42, in <module>
    fields_folder = str(Path(os.getcwd()).parent.parent.parent.parent)
NameError: name 'Path' is not defined
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_55.0/complete_sim.py", line 42, in <module>
    fields_folder = str(Path(os.getcwd()).parent.parent.parent.parent)
NameError: name 'Path' is not defined
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_55.0/complete_sim.py", line 42, in <module>
    fields_folder = str(Path(os.getcwd()).parent.parent.parent.parent)
NameError: name 'Path' is not defined
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_55.0/complete_sim.py", line 42, in <module>
    fields_folder = str(Path(os.getcwd()).parent.parent.parent.parent)
NameError: name 'Path' is not defined
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_55.0/complete_sim.py", line 42, in <module>
    fields_folder = str(Path(os.getcwd()).parent.parent.parent.parent)
NameError: name 'Path' is not defined
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_55.0/complete_sim.py", line 42, in <module>
    fields_folder = str(Path(os.getcwd()).parent.parent.parent.parent)
NameError: name 'Path' is not defined
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_55.0/complete_sim.py", line 42, in <module>
    fields_folder = str(Path(os.getcwd()).parent.parent.parent.parent)
NameError: name 'Path' is not defined
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_55.0/complete_sim.py", line 42, in <module>
    fields_folder = str(Path(os.getcwd()).parent.parent.parent.parent)
NameError: name 'Path' is not defined
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_55.0/complete_sim.py", line 42, in <module>
    fields_folder = str(Path(os.getcwd()).parent.parent.parent.parent)
NameError: name 'Path' is not defined
--------------------------------------------------------------------------
mpirun noticed that the job aborted, but has no info as to the process
that caused that situation.
--------------------------------------------------------------------------
[eu-a6-001-07:14552] 23 more processes have sent help message help-mpi-runtime.txt / mpi_init:warn-fork
[eu-a6-001-07:14552] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
