# Warp
# Origin date: Tue, 12 Nov 2019 15:31:14 -0800
# Local date: Tue, 12 Nov 2019 15:31:14 -0800
# Commit hash: 06ab50e
# /cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/warp.py
# /cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/warpCparallel.cpython-37m-x86_64-linux-gnu.so
# Fri Jan  3 06:29:48 2020
# 24 processors
# import warp time 1.7551512718200684 seconds
# For more help, type warphelp()
--------------------------------------------------------------------------
An MPI process has executed an operation involving a call to the
"fork()" system call to create a child process.  Open MPI is currently
operating in a condition that could result in memory corruption or
other system errors; your MPI job may hang, crash, or produce silent
data corruption.  The use of fork() (or system() or other calls that
create child processes) is strongly discouraged.  

The process that invoked fork was:

  Local host:          eu-a6-007-22 (PID 42771)
  MPI_COMM_WORLD rank: 2

If you are *absolutely sure* that your application will successfully
and correctly survive a call to fork(), you may disable this warning
by setting the mpi_warn_on_fork MCA parameter to 0.
--------------------------------------------------------------------------
('l_fftw_fort', False)
WARNING: module txphysics is not accessible.
WARNING: module desorb is not accessible.
0.0007224415584921976
Simulating ECLOUD in a crab cavity
[eu-a6-007-22:42768] 23 more processes have sent help message help-mpi-runtime.txt / mpi_init:warn-fork
[eu-a6-007-22:42768] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_35.0/complete_sim.py", line 88, in <module>
    sim = warp_pyecloud_sim(**kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 114, in __init__
    electron_background_dist = self.load_elec_density()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 360, in load_elec_density
    self.n_step = dict_init_dist['n_step'][0][0]
KeyError: 'n_step'
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_35.0/complete_sim.py", line 88, in <module>
    sim = warp_pyecloud_sim(**kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 114, in __init__
    electron_background_dist = self.load_elec_density()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 360, in load_elec_density
    self.n_step = dict_init_dist['n_step'][0][0]
KeyError: 'n_step'
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_35.0/complete_sim.py", line 88, in <module>
    sim = warp_pyecloud_sim(**kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 114, in __init__
    electron_background_dist = self.load_elec_density()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 360, in load_elec_density
    self.n_step = dict_init_dist['n_step'][0][0]
KeyError: 'n_step'
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_35.0/complete_sim.py", line 88, in <module>
    sim = warp_pyecloud_sim(**kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 114, in __init__
    electron_background_dist = self.load_elec_density()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 360, in load_elec_density
    self.n_step = dict_init_dist['n_step'][0][0]
KeyError: 'n_step'
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_35.0/complete_sim.py", line 88, in <module>
    sim = warp_pyecloud_sim(**kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 114, in __init__
    electron_background_dist = self.load_elec_density()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 360, in load_elec_density
    self.n_step = dict_init_dist['n_step'][0][0]
KeyError: 'n_step'
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_35.0/complete_sim.py", line 88, in <module>
    sim = warp_pyecloud_sim(**kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 114, in __init__
    electron_background_dist = self.load_elec_density()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 360, in load_elec_density
    self.n_step = dict_init_dist['n_step'][0][0]
KeyError: 'n_step'
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_35.0/complete_sim.py", line 88, in <module>
    sim = warp_pyecloud_sim(**kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 114, in __init__
    electron_background_dist = self.load_elec_density()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 360, in load_elec_density
    self.n_step = dict_init_dist['n_step'][0][0]
KeyError: 'n_step'
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_35.0/complete_sim.py", line 88, in <module>
    sim = warp_pyecloud_sim(**kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 114, in __init__
    electron_background_dist = self.load_elec_density()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 360, in load_elec_density
    self.n_step = dict_init_dist['n_step'][0][0]
KeyError: 'n_step'
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_35.0/complete_sim.py", line 88, in <module>
    sim = warp_pyecloud_sim(**kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 114, in __init__
    electron_background_dist = self.load_elec_density()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 360, in load_elec_density
    self.n_step = dict_init_dist['n_step'][0][0]
KeyError: 'n_step'
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_35.0/complete_sim.py", line 88, in <module>
    sim = warp_pyecloud_sim(**kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 114, in __init__
    electron_background_dist = self.load_elec_density()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 360, in load_elec_density
    self.n_step = dict_init_dist['n_step'][0][0]
KeyError: 'n_step'
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_35.0/complete_sim.py", line 88, in <module>
    sim = warp_pyecloud_sim(**kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 114, in __init__
    electron_background_dist = self.load_elec_density()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 360, in load_elec_density
    self.n_step = dict_init_dist['n_step'][0][0]
KeyError: 'n_step'
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_35.0/complete_sim.py", line 88, in <module>
    sim = warp_pyecloud_sim(**kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 114, in __init__
    electron_background_dist = self.load_elec_density()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 360, in load_elec_density
    self.n_step = dict_init_dist['n_step'][0][0]
KeyError: 'n_step'
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_35.0/complete_sim.py", line 88, in <module>
    sim = warp_pyecloud_sim(**kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 114, in __init__
    electron_background_dist = self.load_elec_density()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 360, in load_elec_density
    self.n_step = dict_init_dist['n_step'][0][0]
KeyError: 'n_step'
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_35.0/complete_sim.py", line 88, in <module>
    sim = warp_pyecloud_sim(**kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 114, in __init__
    electron_background_dist = self.load_elec_density()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 360, in load_elec_density
    self.n_step = dict_init_dist['n_step'][0][0]
KeyError: 'n_step'
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_35.0/complete_sim.py", line 88, in <module>
    sim = warp_pyecloud_sim(**kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 114, in __init__
    electron_background_dist = self.load_elec_density()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 360, in load_elec_density
    self.n_step = dict_init_dist['n_step'][0][0]
KeyError: 'n_step'
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_35.0/complete_sim.py", line 88, in <module>
    sim = warp_pyecloud_sim(**kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 114, in __init__
    electron_background_dist = self.load_elec_density()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 360, in load_elec_density
    self.n_step = dict_init_dist['n_step'][0][0]
KeyError: 'n_step'
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_35.0/complete_sim.py", line 88, in <module>
    sim = warp_pyecloud_sim(**kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 114, in __init__
    electron_background_dist = self.load_elec_density()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 360, in load_elec_density
    self.n_step = dict_init_dist['n_step'][0][0]
KeyError: 'n_step'
Using cosine_3D emission angle distribution.
Secondary emission model: ECLOUD E0=150.0000 s=1.3500
#############################################################
Temp distribution found. Reloading it as initial distribution
#############################################################
/cluster/home/glorenzo/sim_workspace_mpi_py3/venvs/py3/lib/python3.7/site-packages/warp/warp.py:62: UserWarning: there was an error importing gist; if this is a problem, restart python and type 'import gist' for details, otherwise Warp will run OK but with no graphics
  warnings.warn("there was an error importing gist; if this is a problem, restart python and type 'import gist' for details, otherwise Warp will run OK but with no graphics")
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_35.0/complete_sim.py", line 88, in <module>
    sim = warp_pyecloud_sim(**kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 114, in __init__
    electron_background_dist = self.load_elec_density()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 360, in load_elec_density
    self.n_step = dict_init_dist['n_step'][0][0]
KeyError: 'n_step'
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_35.0/complete_sim.py", line 88, in <module>
    sim = warp_pyecloud_sim(**kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 114, in __init__
    electron_background_dist = self.load_elec_density()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 360, in load_elec_density
    self.n_step = dict_init_dist['n_step'][0][0]
KeyError: 'n_step'
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_35.0/complete_sim.py", line 88, in <module>
    sim = warp_pyecloud_sim(**kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 114, in __init__
    electron_background_dist = self.load_elec_density()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 360, in load_elec_density
    self.n_step = dict_init_dist['n_step'][0][0]
KeyError: 'n_step'
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_35.0/complete_sim.py", line 88, in <module>
    sim = warp_pyecloud_sim(**kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 114, in __init__
    electron_background_dist = self.load_elec_density()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 360, in load_elec_density
    self.n_step = dict_init_dist['n_step'][0][0]
KeyError: 'n_step'
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_35.0/complete_sim.py", line 88, in <module>
    sim = warp_pyecloud_sim(**kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 114, in __init__
    electron_background_dist = self.load_elec_density()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 360, in load_elec_density
    self.n_step = dict_init_dist['n_step'][0][0]
KeyError: 'n_step'
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_35.0/complete_sim.py", line 88, in <module>
    sim = warp_pyecloud_sim(**kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 114, in __init__
    electron_background_dist = self.load_elec_density()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 360, in load_elec_density
    self.n_step = dict_init_dist['n_step'][0][0]
KeyError: 'n_step'
Traceback (most recent call last):
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/simulations/scan_efield_cavity/simulations/complete_cavity_Emax_35.0/complete_sim.py", line 88, in <module>
    sim = warp_pyecloud_sim(**kwargs)
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 114, in __init__
    electron_background_dist = self.load_elec_density()
  File "/cluster/home/glorenzo/sim_workspace_mpi_py3/WarPyECLOUD/warp_pyecloud_sim.py", line 360, in load_elec_density
    self.n_step = dict_init_dist['n_step'][0][0]
KeyError: 'n_step'
--------------------------------------------------------------------------
mpirun noticed that the job aborted, but has no info as to the process
that caused that situation.
--------------------------------------------------------------------------
